source "https://github.com/djs66256/DDDevelopCocoaPodsRepos.git"
source "https://github.com/CocoaPods/Specs.git"
platform :ios, '9.0'
use_frameworks!

pod "Alamofire", '~> 3.4'
pod "YYModel", '~>1.0.4'
pod "SwiftyJSON"

pod "DDFileCache"

